import type { CompanionAssetBinding } from "@agent-factory/companion-contracts";
import type { GraphEditOperation, GraphIR, GraphNode, GraphSelection } from "@agent-factory/companion-graph-domain";
import { functionRoles, graphChannels, graphControlKinds } from "@agent-factory/companion-graph-domain";

export function ElementInspector({ graph, selection, assetBindings, errors, onStage, onDelete, developmentPanel }: { graph: GraphIR; selection: GraphSelection | null; assetBindings: CompanionAssetBinding[]; errors: Array<{ path: string; message: string }>; onStage(operations: GraphEditOperation[]): void; onDelete(selection: GraphSelection): void; developmentPanel?: React.ReactNode }) {
  if (!selection) return <aside className="element-inspector empty" aria-labelledby="inspector-title"><p className="eyebrow">Inspector</p><h2 id="inspector-title">요소를 선택하세요.</h2><p>선택과 저장 전 operation이 MCP Context에 바로 공유됩니다.</p></aside>;
  const element = selection.kind === "node" ? graph.nodes.find((entry) => entry.id === selection.id) : selection.kind === "edge" ? graph.edges.find((entry) => entry.id === selection.id) : graph.regions.find((entry) => entry.id === selection.id);
  if (!element) return null;
  return <aside className="element-inspector" aria-labelledby="inspector-title"><div className="inspector-heading"><div><p className="eyebrow">Inspector · {selection.kind}</p><h2 id="inspector-title">{"label" in element ? element.label : element.id}</h2></div><button type="button" className="danger-action" onClick={() => onDelete(selection)}>삭제</button></div><dl className="element-facts"><div><dt>ID</dt><dd><code>{element.id}</code></dd></div>{selection.kind === "node" ? <div><dt>Kind</dt><dd>{(element as GraphNode).node_kind}</dd></div> : null}</dl>{selection.kind === "node" ? <NodeFields node={element as GraphNode} assetBindings={assetBindings} onReplace={(value) => onStage([{ op: "replace", target: "node", id: value.id, value }])} /> : selection.kind === "edge" ? <EdgeFields graph={graph} edge={element as GraphIR["edges"][number]} onReplace={(value) => onStage([{ op: "replace", target: "edge", id: value.id, value }])} /> : <RegionFields graph={graph} region={element as GraphIR["regions"][number]} onReplace={(value) => onStage([{ op: "replace", target: "region", id: value.id, value }])} />}{errors.map((error) => <p className="field-error" key={error.path}><code>{error.path}</code> {error.message}</p>)}{developmentPanel}</aside>;
}

function NodeFields({ node, assetBindings, onReplace }: { node: GraphNode; assetBindings: CompanionAssetBinding[]; onReplace(node: GraphNode): void }) {
  const replace = (patch: Partial<GraphNode>) => onReplace({ ...node, ...patch } as GraphNode);
  const refs = (type: CompanionAssetBinding["asset_type"]) => assetBindings.filter((binding) => binding.asset_type === type).map((binding) => binding.asset_id);
  return <div className="inspector-fields"><Field label="Label"><input value={node.label} maxLength={120} onChange={(event) => replace({ label: event.target.value })} /></Field>{node.node_kind === "agent" ? <><Field label="Bound Agent"><select value={node.agent_ref} onChange={(event) => replace({ agent_ref: event.target.value } as Partial<GraphNode>)}>{options(refs("agent"), node.agent_ref)}</select></Field><Field label="Available Tools"><select multiple value={node.available_tools.map((tool) => tool.tool_ref)} onChange={(event) => replace({ available_tools: [...event.target.selectedOptions].map((option) => ({ tool_ref: option.value, invocation_control: "agent" as const })) } as Partial<GraphNode>)}>{refs("tool").map((value) => <option key={value}>{value}</option>)}</select></Field></> : null}{node.node_kind === "tool" ? <Field label="Bound Tool"><select value={node.tool_ref} onChange={(event) => replace({ tool_ref: event.target.value } as Partial<GraphNode>)}>{options(refs("tool"), node.tool_ref)}</select></Field> : null}{node.node_kind === "subworkflow" ? <Field label="Bound Workflow"><select value={node.workflow_ref} onChange={(event) => replace({ workflow_ref: event.target.value } as Partial<GraphNode>)}>{options(refs("workflow"), node.workflow_ref)}</select></Field> : null}{node.node_kind === "function" ? <Field label="Role"><select value={node.role} onChange={(event) => replace({ role: event.target.value } as Partial<GraphNode>)}>{functionRoles.map((role) => <option key={role}>{role}</option>)}</select></Field> : null}{node.node_kind === "human_input" ? <><Field label="Message"><textarea value={node.human_input_contract.message} onChange={(event) => replace({ human_input_contract: { ...node.human_input_contract, message: event.target.value } } as Partial<GraphNode>)} /></Field><Field label="Choices"><input value={(node.human_input_contract.choice_options ?? []).join(", ")} onChange={(event) => replace({ human_input_contract: { ...node.human_input_contract, choice_options: csv(event.target.value) } } as Partial<GraphNode>)} /></Field></> : null}<p className="field-help">Node kind는 바꿀 수 없습니다. Asset ref는 이 App에 추가된 정확한 binding에서만 선택합니다.</p></div>;
}

function EdgeFields({ graph, edge, onReplace }: { graph: GraphIR; edge: GraphIR["edges"][number]; onReplace(edge: GraphIR["edges"][number]): void }) {
  const replace = (patch: Partial<typeof edge>) => onReplace({ ...edge, ...patch }); const control = (patch: Partial<typeof edge.control>) => replace({ control: { ...edge.control, ...patch } });
  return <div className="inspector-fields"><div className="field-grid"><Field label="From"><select value={edge.from} onChange={(event) => replace({ from: event.target.value })}>{graph.nodes.map((node) => <option key={node.id} value={node.id}>{node.label}</option>)}</select></Field><Field label="To"><select value={edge.to} onChange={(event) => replace({ to: event.target.value })}>{graph.nodes.map((node) => <option key={node.id} value={node.id}>{node.label}</option>)}</select></Field></div><Field label="Control"><select value={edge.control.kind} onChange={(event) => control({ kind: event.target.value as typeof edge.control.kind })}>{graphControlKinds.map((kind) => <option key={kind}>{kind}</option>)}</select></Field><Field label="Condition"><input value={edge.control.condition ?? ""} placeholder="null" onChange={(event) => control({ condition: event.target.value.trim() || null })} /></Field><Field label="Accepted aliases"><input value={edge.control.accepted_aliases.join(", ")} onChange={(event) => control({ accepted_aliases: csv(event.target.value) })} /></Field><label className="check-field"><input type="checkbox" checked={edge.control.default} onChange={(event) => control({ default: event.target.checked })} /> Default route</label><Field label="Channel"><select value={edge.channel ?? ""} onChange={(event) => replace({ channel: event.target.value ? event.target.value as typeof edge.channel : null })}><option value="">null</option>{graphChannels.map((channel) => <option key={channel}>{channel}</option>)}</select></Field></div>;
}

function RegionFields({ graph, region, onReplace }: { graph: GraphIR; region: GraphIR["regions"][number]; onReplace(region: GraphIR["regions"][number]): void }) {
  const replace = (patch: Partial<typeof region>) => onReplace({ ...region, ...patch });
  return <div className="inspector-fields"><Field label="Kind"><select value={region.kind} onChange={(event) => replace({ kind: event.target.value as typeof region.kind })}><option>parallel</option><option>loop</option></select></Field><Field label="Parent"><select value={region.parent_region_id ?? ""} onChange={(event) => replace({ parent_region_id: event.target.value || null })}><option value="">없음</option>{graph.regions.filter((entry) => entry.id !== region.id).map((entry) => <option key={entry.id}>{entry.id}</option>)}</select></Field><NodeChecks label="Members" graph={graph} selected={region.node_ids} onChange={(node_ids) => replace({ node_ids, entry_node_ids: region.entry_node_ids.filter((id) => node_ids.includes(id)), exit_node_ids: region.exit_node_ids.filter((id) => node_ids.includes(id)) })} /><NodeChecks label="Entry" graph={graph} candidates={region.node_ids} selected={region.entry_node_ids} onChange={(entry_node_ids) => replace({ entry_node_ids })} /><NodeChecks label="Exit" graph={graph} candidates={region.node_ids} selected={region.exit_node_ids} onChange={(exit_node_ids) => replace({ exit_node_ids })} /></div>;
}

function NodeChecks({ label, graph, candidates, selected, onChange }: { label: string; graph: GraphIR; candidates?: string[]; selected: string[]; onChange(ids: string[]): void }) { const nodes = candidates ? graph.nodes.filter((node) => candidates.includes(node.id)) : graph.nodes; return <fieldset className="node-checks"><legend>{label}</legend>{nodes.map((node) => <label key={node.id}><input type="checkbox" checked={selected.includes(node.id)} onChange={(event) => onChange(event.target.checked ? [...selected, node.id] : selected.filter((id) => id !== node.id))} />{node.label}</label>)}</fieldset>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field-label"><span>{label}</span>{children}</label>; }
function csv(value: string): string[] { return value.split(",").map((entry) => entry.trim()).filter(Boolean); }
function options(values: string[], current: string) { return [...new Set([current, ...values])].map((value) => <option key={value}>{value}</option>); }
